---

- name: Ensure Garage group is created
  ansible.builtin.group:
    name: "{{ garage_user_username }}"
    gid: "{{ garage_user_gid }}"
    state: present

- name: Ensure Garage user is created
  ansible.builtin.user:
    name: "{{ garage_user_username }}"
    uid: "{{ garage_user_uid }}"
    group: "{{ garage_user_username }}"
    state: present

- name: Ensure Garage network is created in Docker
  community.docker.docker_network:
    name: "{{ garage_docker_network }}"
    driver: bridge

- name: Ensure Garage path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0700
    owner: "{{ garage_user_uid }}"
    group: "{{ garage_user_gid }}"
  with_items:
    - {path: "{{ garage_base_path }}", when: true}
    - {path: "{{ garage_config_path }}", when: true}
    - {path: "{{ garage_meta_path }}", when: true}
    - {path: "{{ garage_data_path }}", when: true}

- name: Ensure Garage node data paths exists
  ansible.builtin.file:
    path: "{{ item.data_path }}"
    state: directory
    mode: 0700
    owner: "{{ garage_user_uid }}"
    group: "{{ garage_user_gid }}"
  loop: "{{ garage_nodes }}"
#  when: not item.gateway

- name: Ensure Garage node metadata paths exists
  ansible.builtin.file:
    path: "{{ item.metadata_path }}"
    state: directory
    mode: 0700
    owner: "{{ garage_user_uid }}"
    group: "{{ garage_user_gid }}"
  loop: "{{ garage_nodes }}"


- name: Ensure Garage traefik labels are installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ garage_config_path }}/labels_{{ item.name }}"
    owner: "{{ garage_user_uid }}"
    group: "{{ garage_user_gid }}"
    mode: 0640
  loop: "{{ garage_nodes }}"
  when: garage_container_labels_traefik_enabled

- name: Ensure garage node configuration is deployed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/garage_node.toml.j2"
    dest: "{{ garage_config_path }}/garage_{{ item.name }}.toml"
    owner: "{{ garage_user_uid }}"
    group: "{{ garage_user_gid }}"
    mode: 0640
  loop: "{{ garage_nodes }}"

- name: Ensure Garage container image is pulled
  community.docker.docker_image:
    name: "{{ garage_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure garage.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/garage_node.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/garage-{{ item.name }}.service"
    mode: 0644
  loop: "{{ garage_nodes }}"
